server:
  port: 23111
spring:
  application:
    name: sports
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      failFast: true
      profile: dev

encrypt:
  failOnError: true
Aliyun:
  FileCenter:
    STORAGE_PATH: http://yyssb.ifitmix.com
  ENDPOINT: http://oss-cn-shenzhen.aliyuncs.com
  ACCESS_ID: sSkFTSmk7h8kzjYi
  ACCESS_KEY: j2M57zDaJ5X6wAmzKtGEqQSR0MwTk8
  BUCKET_NAME: igeekery
#logging:
#  level:
#    org:
#      springframework: DEBUG


