spring:
  application:
    name: auth-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
    initialize: false
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      failFast: true
      profile: dev
encrypt:
  failOnError: true
server:
  port: 9999
  context-path: /uaa
security:
  sessions: stateless
  basic:
    enabled: false