encrypt:
  failOnError: true



#security:
#  sessions: stateless
#  oauth2:
#    resource:
#      loadBalanced: true #必须要有 负责获取不到user信息
#      id: gateway-service
#      user-info-uri: http://auth-service/uaa/user # auth-server 是注册到eureka的服务名称
#      prefer-token-info: false # 不使用/oauth/check_token,因为不能负载均衡 使用在auth-server端实现的 /user api.
#security:
#  oauth2:
#    resource:
##      token-info-uri:
#        token-info-uri: http://localhost:9999/uaa/oauth/check_token
##      user-info-uri: http://auth-service/uaa/user
##      prefer-token-info: false
#    client:
#      clientId: zhangtao
#      clientSecret: zhangtao
#      userAuthorizationUri: http://auth-service/uaa/oauth/authorize
#      accessTokenUri: http://auth-service/uaa/oauth/token
#      grantType: client_credentials
#      scope: app
#  basic:
#    enabled: false
#logging:
#  level:
#    org.springframework.security: debug