server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
           search-locations: classpath:/shared
#        git:
#          uri: https://github.com/zhangtao0/ifitmix-repo
#          basedir: target/config
#          searchPaths: "*"

    stream:
      kafka:
        binder:
          brokers: 10.10.8.238:9092,10.10.8.238:9093,10.10.8.238:9094
          zkNodes: 10.10.8.238:2181,10.10.8.238:2182,10.10.8.238:2183
          offsetUpdateTimeWindow: 10000
          #offsetUpdateCount: 0
          requiredAcks: 1
          minPartitionCount: 1
          replicationFactor: 1
#          brokers: 192.168.1.124:9092
#          zk-nodes: 192.168.1.124:2181
        bindings:
          input:
            consumer:
              autoCommitOffset: true
              startOffset: earliest
              headerMode: raw
          output:
            producer:
              bufferSize: 16384
              sync: true
              batchTimeout: 0
#              bootstrapServers: 10.10.8.238:9092
  profiles:
     active: native


management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

  client:
    serviceUrl:
      defaultZone: http://10.10.8.238:8761/eureka/